[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
leptos = { version = "0.5.4", features = ["ssr", "nightly"] }
quote = "1.0.33"
syn = "2.0.43"
