name: Publish
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup toolchain install nightly
    - run: rustup target add wasm32-unknown-unknown --toolchain nightly
    - run: cargo install --locked cargo-leptos
      continue-on-error: true
    - name: Build
      run: cargo +nightly leptos build -r
    - name: Generate
      run: cargo +nightly run -r --features=ssr
    - uses: actions/upload-pages-artifact@v3
      with:
        path: "target/site/pkg/"
        
  deploy: 
    runs-on: ubuntu-latest
    needs: ["build"]
    permissions:
      id-token: write
      actions: read
      pages: write
    steps:
    - uses: actions/deploy-pages@v4.0.2
